# Generated by Django 5.1.7 on 2025-03-19 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=30, null=True)),
                ('complaintImage', models.FileField(null=True, upload_to='file')),
                ('solvedImage', models.FileField(null=True, upload_to='file')),
                ('status', models.CharField(max_length=30, null=True)),
                ('date', models.DateField(null=True)),
                ('authorityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority')),
                ('loginId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
