# Generated by Django 5.1.7 on 2025-03-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_complaint_latitude_complaint_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='loginId',
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizenId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='myapp.citizen'),
            preserve_default=False,
        ),
    ]
